//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorNFE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinatario
    {
        public int DestinatarioId { get; set; }
        public string CNPJ { get; set; }
        public Nullable<int> IndIEDest { get; set; }
        public string InscricaoEstadual { get; set; }
        public string ISUF { get; set; }
        public string NomeRazao { get; set; }
        public string Fone { get; set; }
        public string CEP { get; set; }
        public string Logradouro { get; set; }
        public Nullable<int> NumeroCasa { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public int CidadeCodigo { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public int PaisCodigo { get; set; }
        public string Pais { get; set; }
        public string Email { get; set; }
    }
}
