//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorNFE.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeradorEntities : DbContext
    {
        public GeradorEntities()
            : base("name=GeradorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emitente> Emitente { get; set; }
        public virtual DbSet<Transportador> Transportador { get; set; }
        public virtual DbSet<Destinatario> Destinatario { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
    }
}
